emailtemplate/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^main/', include('main.urls', namespace='main')),
]

main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='main/index.html'), name='home'),
    url(r'^email_one/$', views.email_txt, name='email_txt'),
    url(r'^email_two/$', views.email_html, name='email_html'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.template.loader import get_template, render_to_string


def email_txt(request):
    subject = "I am a text email"
    to = ['buddy@buddylindsey.com']
    from_email = 'test@example.com'

    ctx = {
        'user': 'buddy',
        'amt': 5,
        'purchase': 'Books'
    }

    body = render_to_string('main/email.txt', ctx)

    EmailMessage(subject=subject,
                 body=body,
                 from_email=from_email,
                 to=to).send()
    return HttpResponse('Plain Text Email Sent')


def email_html(request):
    """An alternate approach is to use:
    from django.core.mail import EmailMultiAlternatives
    https://docs.djangoproject.com/en/1.11/topics/email/#sending-alternative-content-types
    """

    subject = "I am an HTML email"
    to = ['buddy@buddylindsey.com']
    from_email = 'test@example.com'

    ctx = {
        'user': 'buddy',
        'amt': 5,
        'purchase': 'Books'
    }

    body = get_template('main/email.html').render(ctx)
    msg = EmailMessage(subject=subject,
                       body=body,
                       from_email=from_email,
                       to=to)
    msg.content_subtype = 'html'
    msg.send()
    return HttpResponse('HTML Email Sent')

templates/base.html
{% load static %}
<!doctype html>
<html>
  <head>
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" type="text/css" rel="stylesheet" />
  </head>
  <body>
    <div class="container">
      <h2>GoDjango</h2>
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

templates/main/email.html
Hello <strong>{{ user }}</strong><br />
<p>
This is fun stuff going on.
</p>
<p>
You have purchased: <strong>{{ amt }}{{ purchase }}</strong>
</p>
<p>
Thanks
</p>

templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h3>Episode 19: Using templates for Sending Emails</h3>
  <ul class="list-group">
    <li class="list-group-item"><a href='{% url "main:email_txt" %}'>Send Text Email</a></li>
    <li class="list-group-item"><a href='{% url "main:email_html" %}'>Send HTML Email</a></li>
  </ul>
{% endblock %}